name: "Terraform-destroy"
on:
  workflow_dispatch:
    inputs:
      infra_env:
        description: 'Environment of infrastructure'
        required: true
        default: 'test'
env:
  ENV: test
  BUCKET_NAME: terraform-demo-instnce-bucket
  DYNAMO_DB : terraform-demo-instance-table
defaults:
  run:
    shell: bash
jobs:  
  terraform:
    name: 'destroy ceq web infra'
    runs-on: [ubuntu-latest]
    #runs-on: ${{ matrix.os }}
    #strategy:
      #fail-fast: false
      #matrix:
        #os: [ubuntu-latest]

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1


    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}    
    
    - name: Terraform Init
      run: terraform init -backend-config="bucket=$BUCKET_NAME" -backend-config="key=${{ env.TF_VAR_STATE_FILE }}" -backend-config="dynamodb_table=$DYNAMO_DB" -backend-config="encrypt=true"
      #run: terraform init -no-color -reconfigure -force-copy -backend-config="bucket=$BUCKET_NAME" -backend-config="key=${{ env.TF_VAR_STATE_FILE }}" -backend-config="dynamodb_table=$DYNAMO_DB" -backend-config="encrypt=true"
      env:
        TF_VAR_STATE_FILE: "$ENV-${{ github.event.repository.name }}.tfstate"  

    - name: Terraform Destroy
      #if: github.ref == 'refs/heads/master' && github.event_name == 'push'      
      #run: terraform destroy -auto-approve -var-file="$ENV/terraform.tfvars" -input=false -lock=false
      run: terraform apply -auto-approve